services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - app_network
    env_file:
      - ./apps/frontend/.env
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network
    env_file:
      - ./apps/backend/.env

  caddy:
    image: caddy:2.9-builder-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    networks:
      - app_network
    depends_on:
      - web
      - api
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname

volumes:
  caddy_data:
  caddy_config:

networks:
  app_network:
